# Generated by Django 3.1.7 on 2021-02-28 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('line_of_business', models.CharField(max_length=200)),
                ('organisation_type', models.CharField(max_length=200)),
                ('business_registration_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=200)),
                ('organisation_description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('premium', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=200)),
                ('is_super', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=200)),
                ('payment', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('policies', models.ManyToManyField(to='account.Policy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('is_special', models.BooleanField(default=False)),
                ('policies', models.ManyToManyField(to='account.Policy')),
            ],
            options={
                'verbose_name': 'benefiaciary',
                'verbose_name_plural': 'beneficiaries',
                'ordering': ('name',),
            },
        ),
    ]
